version: '3.9'

volumes:
  caddy-data:


networks:
  default:
    name: Default
    driver: bridge

services:
  caddy:
    image: ${CADDY_IMAGE}
    networks:
      - default
    restart: always
    volumes:
      - caddy-data:/data
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./logs/caddy/:/var/log/caddy
      - ./certs/:/data/certs
    ports:
      - "80:80"
      - "443:443"
